name: Dev Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            artifact_name: gemini-keychecker
            release_name: gemini-keychecker-linux-x86_64
          - target: aarch64
            target_triple: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
            artifact_name: gemini-keychecker
            release_name: gemini-keychecker-linux-aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target_triple }}

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Create release package
        run: |
          mv target/${{ matrix.target_triple }}/release/${{ matrix.artifact_name }} .
          mkdir -p release-package
          mv ${{ matrix.artifact_name }} release-package/
          cd release-package
          zip -r ../${{ matrix.release_name }}.zip .

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.release_name }}
          path: ${{ matrix.release_name }}.zip
          retention-days: 30

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-pc-windows-msvc
            artifact_name: gemini-keychecker.exe
            release_name: gemini-keychecker-windows-x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target_triple }}

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Create release package
        run: |
          mkdir -p release-package
          mv target/${{ matrix.target_triple }}/release/${{ matrix.artifact_name }} release-package/
          Compress-Archive -Path 'release-package\*' -DestinationPath "${{ matrix.release_name }}.zip" -CompressionLevel Optimal -Force

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.release_name }}
          path: ${{ matrix.release_name }}.zip
          retention-days: 30

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-apple-darwin
            artifact_name: gemini-keychecker
            release_name: gemini-keychecker-macos-x86_64
          - target: aarch64
            target_triple: aarch64-apple-darwin
            artifact_name: gemini-keychecker
            release_name: gemini-keychecker-macos-aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target_triple }}

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Create release package
        run: |
          mv target/${{ matrix.target_triple }}/release/${{ matrix.artifact_name }} .
          mkdir -p release-package
          mv ${{ matrix.artifact_name }} release-package/
          cd release-package
          zip -r ../${{ matrix.release_name }}.zip .

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.release_name }}
          path: ${{ matrix.release_name }}.zip
          retention-days: 30
